.PHONY: downloads normalizations

normalizations:
	- pipenv run python -c "import normalizer; normalizer.normalize_all()"

validate:
	- pipenv run python -c "import validator; validator.validate_all()"

downloads:
	- pipenv run python -c "import downloader; downloader.download_all()"

test:
	- pipenv run python -m unittest discover -p tests.py
