normalize:
	- pipenv run python -c "import normalizer; normalizer.normalize_all()"

download:
	- pipenv run python -c "import downloader; downloader.download_all()"

test:
	- pipenv run python -m unittest discover -p tests.py
